#!/usr/bin/env bash
# arch_type="moe-mini-sparse-shared"
# arch_type="tabrm-piecewiselinear"
# arch_type="tabrmv2-piecewiselinear"
# arch_type="tabrmoev3-periodic"
# arch_type="tabrmoev3-periodic"
# reproducing tabm-mini-piecewiselinear
# arch_type="reproduced-tabm-mini-piecewiselinear"
# arch_type="reproduced-tabr-periodic"
arch_type="tabr-pln-periodic"

# data_list=("churn" "house" "adult" "california" "diamond" "otto" "higgs-small" "black-friday" "microsoft" "covtype2")
data_list=(
  "churn"
  "tabred/sberbank-housing"
  "why/regression-cat-medium-0-OnlineNewsPopularity/"
  "tabred/ecom-offers"
  "why/classif-num-medium-0-credit"
  "why/regression-num-medium-0-medical_charges"
  "house"
  "why/classif-num-medium-0-bank-marketing"
  "why/classif-num-medium-0-kdd_ipums_la_97-small"
  "why/classif-cat-medium-0-KDDCup09_upselling"
  "why/classif-num-medium-0-MagicTelescope"
  "why/regression-num-medium-0-fifa"
  "adult"
  "why/regression-num-large-0-year"
  "why/regression-cat-medium-0-house_sales"
  "tabred/maps-routing"
  "california"
  "tabred/cooking-time"
  "why/regression-cat-medium-0-Brazilian_houses"
  "why/regression-num-medium-0-elevators"
  "why/classif-num-large-0-jannis"
  "why/regression-num-medium-0-Ailerons"
  "tabred/delivery-eta"
  "why/classif-num-medium-0-wine"
  "why/regression-num-medium-0-wine_quality"
  "why/classif-num-large-0-MiniBooNE"
  "why/regression-cat-large-0-nyc-taxi-green-dec-2016/"
  "diamond"
  "tabred/homecredit-default"
  "why/classif-num-medium-0-phoneme"

  
  "why/classif-num-medium-1-credit"
  "why/classif-num-medium-1-bank-marketing"
  "why/classif-num-medium-2-bank-marketing"
  "why/classif-num-medium-1-kdd_ipums_la_97-small"
  "why/classif-num-medium-2-kdd_ipums_la_97-small"
  "why/classif-cat-medium-1-KDDCup09_upselling"
  "why/classif-cat-medium-2-KDDCup09_upselling"
  "why/classif-num-medium-1-MagicTelescope"
  "why/classif-num-medium-2-MagicTelescope"
  "why/regression-num-medium-1-fifa"
  "why/regression-cat-medium-1-Brazilian_houses"
  "why/regression-cat-medium-2-Brazilian_houses"
  "why/regression-num-medium-1-elevators"
  "why/regression-num-medium-1-Ailerons"
  "why/regression-num-medium-2-Ailerons"
###########################################################################

  # "why/classif-num-medium-1-wine" # 
  # "why/classif-num-medium-2-wine"
  # "why/classif-num-medium-3-wine"
  # "why/classif-num-medium-4-wine"
  # "why/regression-num-medium-1-wine_quality"
  # "why/regression-num-medium-2-wine_quality"
  # "why/classif-num-medium-1-phoneme"
  # "why/classif-num-medium-2-phoneme"
  # "why/classif-num-medium-3-phoneme"
  # "why/classif-num-medium-4-phoneme"
  # "why/regression-num-medium-0-pol"
  # "why/regression-num-medium-1-pol"
  # "why/regression-num-medium-0-cpu_act"
  # "why/regression-num-medium-1-cpu_act"
  # "why/regression-num-medium-2-cpu_act"
  # "why/regression-num-medium-0-isolet"
  # "why/regression-num-medium-1-isolet"
  # "why/regression-num-medium-2-isolet"
  # "why/regression-cat-medium-0-analcatdata_supreme"
  # "why/regression-cat-medium-1-analcatdata_supreme"
  # "why/regression-cat-medium-2-analcatdata_supreme"
  # "why/regression-cat-medium-3-analcatdata_supreme"
  # "why/regression-cat-medium-4-analcatdata_supreme"
  # "otto"
  # "why/classif-cat-large-0-road-safety"
  # "why/regression-num-medium-0-MiamiHousing2016"
  # "why/regression-num-medium-1-MiamiHousing2016"
  # "why/regression-num-medium-2-MiamiHousing2016"
  # "higgs-small"
  # "why/regression-cat-medium-0-Mercedes_Benz_Greener_Manufacturing"
  # "why/regression-cat-medium-1-Mercedes_Benz_Greener_Manufacturing"
  # "why/regression-cat-medium-2-Mercedes_Benz_Greener_Manufacturing"
  # "why/regression-cat-medium-3-Mercedes_Benz_Greener_Manufacturing"
  # "why/regression-cat-medium-4-Mercedes_Benz_Greener_Manufacturing"
  # "black-friday"
  # "why/regression-cat-large-0-particulate-matter-ukair-2017"
  # "tabred/homesite-insurance"
  # "tabred/weather"
  # "microsoft"
  # "covtype2"
)

for data in "${data_list[@]}"
do
    python bin/go.py exp/${arch_type}/${data}/0-tuning --continue | tee exp/${arch_type}/${data}/0-tuning.log 
done
